# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Mon Nov 15 18:14:55 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder/sub folder
spec:
- template: S1_Template
  scheduledStartDate: 2021-11-15T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- template: S2_Template_2
  scheduledStartDate: 2021-11-15T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
