# Exported from:        http://minserver:5516/
# Release version:      10.2.0-706.113
# Date created:         Mon Jul 26 18:21:26 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder_1
spec:
- pattern: jhkewhf ew fi ewfyewo ffoewf ewyfo ewfoewyf ew foyoewyf oewf ewfoewuofuewo
    ckdsckdshofiuwe foewfw dcwlefoiuewof dchewofcoe o fwlehfohoewfo wef oewfoewuf
    ifbyiewufi ew fef iyewi f ewif yiew fy ewi yfiw yeifdisycidsciewqf ec eofyoewf
    dskcdskvcoiewyovc dskjc
  stages:
  - stage: New Stage
- pattern: pattern1
  stages:
  - stage: New Stage
    transition:
      name: New Transition
      type: delivery.Transition
  - stage: New Stage (1)
  - stage: New Stage (2)
