# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Wed Nov 10 17:24:14 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Samples & Tutorials
spec:
- name: Time trigger
  type: time.Schedule
  releaseTitle: Release created by trigger
  template: Configure Release
  pollType: REPEAT
  periodicity: "500"
  triggerTime: 2021-11-10T17:19:44.142000
