# Exported from:        http://minserver:5516/
# Release version:      23.1.0-rc.3
# Date created:         Fri May 05 16:03:24 IST 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Triggers.yaml
  - Notifications.yaml
  - Templates.yaml
