# Exported from:        http://qe-centos-ha1:5516/
# Release version:      22.1.0-316.341
# Date created:         Thu Mar 17 11:40:47 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Samples & Tutorials
spec:
- name: time trigger test
  type: time.Schedule
  releaseTitle: Test release
  template: Configure Release
  pollType: REPEAT
  periodicity: "10"
  triggerTime: 2022-03-17T11:39:57.780000
