# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Sat Nov 13 15:25:17 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Samples & Tutorials
spec:
- pattern: pattern 1
  stages:
  - stage: New Stage
