# Exported from:        http://Sinthuja:5516/
# Release version:      24.3.0-SNAPSHOT
# Date created:         Mon Jul 15 18:09:33 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Fol1/Fol3
spec:
- name: Folder3 Jenkins
  type: jenkins.Server
  url: http://folder3jenkins.com
