# Exported from:        http://Sinthuja:5516/
# Release version:      24.3.0-SNAPSHOT
# Date created:         Mon Jul 15 18:09:33 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Fol1/Fol3
spec:
- template: find folder id
  scheduledStartDate: 2024-07-11T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: gate
      type: xlrelease.GateTask
      conditions:
      - name: to check
        type: xlrelease.GateCondition
    - name: Find folder id
      type: xlrelease.ScriptTask
      script: |-
        print "getCurrentFolder(): %s" % getCurrentFolder()
        print "getCurrentFolder().id: %s" % getCurrentFolder().id
        print "getCurrentFolder().title: %s" % getCurrentFolder().title
    - name: Jenkins
      type: jenkins.Build
      jenkinsServer: Jenkins server
      jobName: XLR
    - name: Jenkins container - global
      type: containerJenkins.JenkinsBuild
      capabilities:
      - remote
      jenkinsServer: Jenkins container
      jobName: XLR
    - name: Jenkins container- parent
      type: containerJenkins.JenkinsBuild
      capabilities:
      - remote
      jenkinsServer: Jenkins container
      jobName: LRR
    - name: reactive webhook task
      type: webhook.WaitForJsonEvent
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_find_folder_id_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
