# Exported from:        http://minserver:5516/
# Release version:      10.2.0-SNAPSHOT
# Date created:         Fri May 21 15:37:39 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder_1
spec:
- name: My Dashboard
  type: xlrelease.BlankDashboard
  description: testing dashboard
  owner: admin
  tiles:
  - name: Active releases
    type: live.ReleasesTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: Folder_1
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.variable under folder_gr
    value: abc
- name: Jira config
  type: jira.Server
  url: https://digitalai.atlassian.net/
  username: sinthuja@digital.ai
  password: !value "jira_Server_Jira_config_password"
