# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Tue Oct 26 18:25:38 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parentfolder
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.variable1
- pattern: pattern11
  stages:
  - stage: stage1
  - stage: stage2
- pattern: pattern12
  stages:
  - stage: New Stage
- template: Parent template 1
  scheduledStartDate: 2021-10-25T09:00:00+05:30
  dueDate: 2021-10-25T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: task1
      type: xlrelease.Task
    - name: task2
      type: xlrelease.Task
  riskProfile: Default risk profile
- template: Template 2
  scheduledStartDate: 2021-10-25T09:00:00+05:30
  dueDate: 2021-10-25T10:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- name: Dashboard1
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Active releases
    type: live.ReleasesTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Active releases by risk
    type: live.ReleasesByRiskTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Avg. release duration
    type: xlrelease.AvgReleaseDurationTile
- name: Trigger1
  type: git.Poll
  releaseTitle: Release created by trigger
  template: Parent template 1
  gitRepository: My git repo
  commitId: 9a4606076df097d6121779c429876ae26c0a2623
