# Exported from:        http://minserver:5516/
# Release version:      22.1.0-SNAPSHOT
# Date created:         Tue Feb 01 15:16:40 IST 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Base Data
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.github token
  - type: xlrelease.PasswordStringVariable
    key: folder.Jira token
  - type: xlrelease.StringVariable
    key: folder.textvariable
  - type: xlrelease.ListStringVariable
    key: folder.listvariable
