# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Thu Dec 16 18:08:36 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Base Data
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.password1
    value: !value "xlrelease_PasswordStringVariable_folder_password1_value"
- pattern: pattern1
  stages:
  - stage: New Stage
- name: My Dashboard
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Avg. task duration
    type: xlrelease.AvgTaskDurationTile
    row: 0
    col: 0
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    row: 0
    col: 1
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
- name: Time trigger
  type: time.Schedule
  releaseTitle: Release created by trigger
  template: Configure Release
  releaseFolder: ./
  pollType: REPEAT
  periodicity: "600"
  triggerTime: 2021-12-16T18:04:14.180000
