# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Fri Dec 17 18:15:05 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Base Data
spec:
- name: test agility connection
  type: versionone.Server
  url: https://agility.com
