# Exported from:        http://de3468993a42:5516/
# Release version:      22.1.0-302.113
# Date created:         Thu Mar 03 09:25:37 GMT 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Test folder test
spec:
- pattern: dsfd
  stages:
  - stage: New Stage
    transition:
      name: New Transition
      type: delivery.Transition
  - stage: New Stage (1)
  trackedItems:
  - trackedItem: ddd
- template: Template 1_old
  scheduledStartDate: 2022-03-02T03:30:00Z
  phases:
  - phase: New Phase
    tasks:
    - name: task 1
      type: xlrelease.Task
    - name: task 2
      type: xlrelease.Task
  riskProfile: Default risk profile
