# Exported from:        http://minserver:5516/
# Release version:      22.0.0-rc.2
# Date created:         Mon Jan 24 16:05:19 IST 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: test123
spec:
- pattern: pattern123
  stages:
  - stage: stage1
  trackedItems:
  - trackedItem: item1
- template: temp123-edited (1)
  scheduledStartDate: 2022-01-24T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: task21
      type: xlrelease.Task
    - name: task2
      type: xlrelease.Task
  riskProfile: Default risk profile
- name: dash1
  type: xlrelease.BlankDashboard
  owner: hs3
  tiles:
  - name: Active releases
    type: live.ReleasesTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Active releases
    type: live.ReleasesTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Active releases by risk
    type: live.ReleasesByRiskTile
    row: 0
    col: 4
    filters:
    - type: xlrelease.DateFilter
      timeFrame: LAST_MONTH
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
- name: trigger123
  type: git.Poll
  releaseTitle: ddd
  template: temp123-edited (1)
  gitRepository: Global Git repo
  commitId: fdfa01da14210be7c09c7fafa6cb661fd3b4793b
