# Exported from:        http://qe-centos-ha1:5516/
# Release version:      22.0.0-104.113
# Date created:         Tue Jan 11 11:53:27 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Sinthuja
spec:
- template: My Template
  scheduledStartDate: 2022-01-11T04:30:00+01:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
