# Exported from:        http://Jagan-lt10:5516/
# Release version:      23.3.0-SNAPSHOT
# Date created:         Wed Sep 20 15:05:36 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: My folder
spec:
- template: My Workflow 1
  scheduledStartDate: 2023-09-20T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: task1
      type: xlrelease.Task
    - name: task21345
      type: xlrelease.CreateReleaseTask
  kind: WORKFLOW
  disableNotifications: true
  author: admin
  defaultTargetFolder: ./
