# Exported from:        http://minserver:5516/
# Release version:      10.2.0-SNAPSHOT
# Date created:         Tue Jun 29 16:36:40 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder_1
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.ffff
    value: !value "xlrelease_PasswordStringVariable_folder_ffff_value"
  - type: xlrelease.StringVariable
    key: folder.fv
    value: def
