# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Wed Nov 24 17:01:08 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: webhook config 2
  type: events.PostWebhookEndpoint
  path: webhookstestpath
  authentication:
    type: events.NoAuthentication
- name: Local Jenkins-nameedited
  type: jenkins.Server
  url: http://192.168.1.16:8080/
  username: ghgh
- name: Jira
  type: jira.Server
  url: https://digitalai.atlassian.net/jira/
- name: Nexus server
  type: nexus.Server
  variableMapping:
    password: "${global.github token}"
  url: https://localhost:8081
- name: SVN server
  type: svn.Repository
  url: https://subversion
- directory: sub folder
  children:
  - name: Sub folder Jenkins sever
    type: jenkins.Server
    variableMapping:
      password: "${global.github token}"
    url: http://192.168.1.16:8080/
    username: testuser
