# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Tue Nov 16 15:41:17 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- template: T2
  scheduledStartDate: 2021-11-16T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- name: Time trigger
  type: time.Schedule
  releaseTitle: R2
  template: T2
  pollType: REPEAT
  periodicity: "50000"
  triggerTime: 2021-11-16T15:40:54.078000
- directory: sub folder
  children:
  - template: S1_Template
    scheduledStartDate: 2021-11-15T09:00:00+05:30
    dueDate: 2021-11-15T10:00:00+05:30
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
  - template: S2_Template_2
    scheduledStartDate: 2021-11-15T09:00:00+05:30
    dueDate: 2021-11-15T10:00:00+05:30
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
- directory: subfolder2
  children:
  - template: Template111
    scheduledStartDate: 2021-11-15T09:00:00+05:30
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
