# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Mon Nov 15 19:14:58 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: parent folder git config
  type: git.Repository
  variableMapping:
    password: "${global.github token}"
  url: https://github.com/Sinthujah/TestRepo
  username: sinthujah
- template: T1
  scheduledStartDate: 2021-11-15T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- directory: sub folder
  children:
  - template: S1_Template
    scheduledStartDate: 2021-11-15T09:00:00+05:30
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
  - template: S2_Template_2
    scheduledStartDate: 2021-11-15T09:00:00+05:30
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
