# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Fri Nov 19 16:10:18 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: git poll trigger
  type: git.Poll
  releaseTitle: tttt
  template: T4
  gitRepository: Global Git repo
  commitId: 37e89c180880cadeab019718689e5552df6406f0
