# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Tue Nov 23 15:40:00 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: git poll trigger
  type: git.Poll
  releaseTitle: tttt
  template: T4
  gitRepository: Global Git repo
  commitId: 17d54f305bc6f4dcf792b37b8b0259a5e05fc4ff
- name: Jira trigger
  type: jira.IssueTrigger
  releaseTitle: dd
  template: T4
  jql: ddd
  server: Jira
