# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Fri Nov 19 16:31:27 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: git poll trigger
  type: git.Poll
  releaseTitle: tttt
  template: T4
  gitRepository: Global Git repo
  commitId: 4ad8376a3f54feecba3478f5c82d7312c8dbc381
- name: Jira trigger
  type: jira.IssueTrigger
  releaseTitle: dd
  template: T4
  jql: ddd
  server: Jira
