# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Tue Nov 23 15:37:38 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: git poll trigger
  type: git.Poll
  releaseTitle: tttt
  template: T4
  gitRepository: Global Git repo
  commitId: d5c7742dcdf4e36075b9671490407d1744fd792a
- name: eee
  type: jira.IssueTrigger
  enabled: false
  releaseTitle: dewd
  template: T4
  jql: de
  server: Jira
- name: Nexus trigger
  type: nexus.PublishedArtifact
  releaseTitle: dewd
  template: T4
  groupId: vv
  artifactId: vv
  server: Nexus server
  repositoryId: ewe
