# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Fri Nov 19 16:41:23 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: git poll trigger
  type: git.Poll
  releaseTitle: tttt
  template: T4
  gitRepository: Global Git repo
  commitId: 4837fc4a65920557df9cfd2cdfaea79e35f7bc71
- name: Nexus trigger
  type: nexus.PublishedArtifact
  releaseTitle: dewd
  template: T4
  groupId: vv
  artifactId: vv
  server: Nexus server
  repositoryId: ewe
- name: svn trigger
  type: svn.Poll
  releaseTitle: dd
  template: T4
  svnRepository: SVN server
