# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Wed Nov 17 15:21:23 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: Time trigger-edit
  type: time.Schedule
  releaseTitle: R2-release
  template: T2-edit
  pollType: REPEAT
  periodicity: "50000"
  triggerTime: 2021-11-16T15:58:35.962000
