# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Wed Nov 17 16:01:59 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: webhook event trigger
  type: events.EventBasedTrigger
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: r3
  - type: xlrelease.StringValue
    targetProperty: template
    value: T2-edit
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: webhook config 1
  eventType: events.HttpRequestEvent
- name: Time trigger-edit
  type: time.Schedule
  releaseTitle: R2-release
  template: T2-edit
  pollType: REPEAT
  periodicity: "50000"
  triggerTime: 2021-11-17T15:23:49.662000
