# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Wed Nov 24 17:06:04 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: parent folder
spec:
- name: webhook config 2
  type: events.PostWebhookEndpoint
  path: webhookstestpath
  authentication:
    type: events.NoAuthentication
- name: Local Jenkins-nameedited
  type: jenkins.Server
  url: http://192.168.1.16:8080/
  username: ghgh
- name: Jira
  type: jira.Server
  url: https://digitalai.atlassian.net/jira/
- name: Nexus server
  type: nexus.Server
  variableMapping:
    password: "${global.github token}"
  url: https://localhost:8081
- name: SVN server
  type: svn.Repository
  url: https://subversion
- name: git poll trigger
  type: git.Poll
  releaseTitle: tttt
  template: T4
  gitRepository: Global Git repo
  commitId: 6f85b66e60b12c3d838c4922bb3f5fb9270aa671
- name: eee
  type: jira.IssueTrigger
  releaseTitle: dewd
  template: T4
  jql: de
  server: Jira
- name: Nexus trigger
  type: nexus.PublishedArtifact
  enabled: false
  releaseTitle: dewd
  template: T4
  groupId: vv
  artifactId: vv
  server: Nexus server
  repositoryId: ewe
- directory: sub folder
  children:
  - name: Sub folder Jenkins sever
    type: jenkins.Server
    variableMapping:
      password: "${global.github token}"
    url: http://192.168.1.16:8080/
    username: testuser
