# Exported from:        http://Jagan-lt10:5516/
# Release version:      23.3.0-beta.5
# Date created:         Mon Aug 14 15:01:49 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Digital.ai - Official/Workflows
spec:
- template: normal template1234
  scheduledStartDate: 2023-08-14T09:00:00+05:30
  dueDate: 2023-08-14T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: "111"
      type: xlrelease.Task
    - name: "222"
      type: xlrelease.Task
    - name: "333"
      type: xlrelease.Task
  riskProfile: Default risk profile
- directory: ArgoCD
- directory: Digital.ai Deploy
