# Exported from:        http://minserver:5516/
# Release version:      10.2.0-SNAPSHOT
# Date created:         Thu May 20 16:09:01 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder_1
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.ffff
    value: !value "xlrelease_PasswordStringVariable_folder_ffff_value"
  - type: xlrelease.StringVariable
    key: folder.fv
    value: def
- name: fol1_webhook_event
  type: events.PostWebhookEndpoint
  path: github_push2
  authentication:
    type: events.NoAuthentication
- name: git_config_at_folder_level
  type: git.Repository
  variableMapping:
    password: "${global.github_token}"
  url: https://github.com/Sinthujah/TestRepo
  username: sinthujah
- name: Testing git hub
  type: xlrelease.GitHubScmConnectorConfig
  repository: Sinthujah/TestRepo
  credential:
    type: xlrelease.GitHubOAuth2Token
    token: !value "xlrelease_GitHubOAuth2Token_token"
- template: Test Template 2
  scheduledStartDate: 2021-04-29T09:00:00+05:30
  dueDate: 2021-04-29T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: Task 12
      type: xlrelease.Task
  riskProfile: Default risk profile
- template: Test template 1
  scheduledStartDate: 2021-04-28T09:00:00+05:30
  dueDate: 2021-04-28T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: "${folder.variable under folder_gr}"
      type: xlrelease.Task
    - name: create release task 1
      type: xlrelease.CreateReleaseTask
      riskProfile: Default risk profile
      template: "${folder.fv}"
      folder: "${folder.fv}"
    - name: gate teask
      type: xlrelease.GateTask
      conditions:
      - name: New Condition
        type: xlrelease.GateCondition
      dependencies:
      - type: xlrelease.Dependency
        targetId: "${folder.fv}"
    - name: jenkins
      type: jenkins.Build
      jenkinsServer: localjenkins
      jobName: test
      variableMapping:
        pythonScript.apiToken: "${folder.ffff}"
    - name: jython task
      type: xlrelease.ScriptTask
      script: print(folderVariables)
  riskProfile: Default risk profile
- name: Trigger using webhook event
  type: events.EventBasedTrigger
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: Release created by the webhook event trigger under long folder name
  - type: xlrelease.StringValue
    targetProperty: template
    value: Test template 1
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: Long folder name kdweh12u3oi21embckjfih243iu1834989e3bekj32keh32e9832e21ekj21eh
      e3iu2ye832 ej32geiy328ey9832 iuiu32yeiu32 iueiu32yeiu32e geiu32eiuy32ue iueiu32yeiu32eiu32e
      jchdsiuyfiewy3 22n3iue32e ueiu32iueiu32he32ehjbjbej32eiu32uyei8 iuhduihiuew
      iuei
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: fol1_webhook_event
  eventType: events.HttpRequestEvent
- name: Trigger with empty folder test 1
  type: events.EventBasedTrigger
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: release 1234
  - type: xlrelease.StringValue
    targetProperty: template
    value: Test template 1
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: fol1_webhook_event
  eventType: events.HttpRequestEvent
- name: Webhook event Trigger - no folder selected
  type: events.EventBasedTrigger
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: Release - no folder selected
  - type: xlrelease.StringValue
    targetProperty: template
    value: Test template 1
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: fol1_webhook_event
  eventType: events.HttpRequestEvent
- name: Git poll trigger - no folder
  type: git.Poll
  description: testing the triggers
  periodicity: "5"
  releaseTitle: Release created by a trigger 1
  template: Test template 1
  gitRepository: git_config_at_folder_level
  commitId: 8f14a26bbd16163de393e38361de35b9e6b04a47
- name: Trigger 1
  type: git.Poll
  releaseTitle: release by gr
  template: Test template 1
  releaseFolder: Folder_3
  gitRepository: git_config_at_folder_level
  commitId: 8f14a26bbd16163de393e38361de35b9e6b04a47
- name: Trigger 2
  type: git.Poll
  releaseTitle: Release to be created under 'folder3' by the trigger
  template: Test template 1
  releaseFolder: Folder_3
  gitRepository: git_config_at_folder_level
  commitId: 8f14a26bbd16163de393e38361de35b9e6b04a47
