# Exported from:        http://Sinthuja:5516/
# Release version:      24.3.0-SNAPSHOT
# Date created:         Fri Jul 19 10:56:02 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: fol1/subfol2
spec:
- pattern: pattern 2
  stages:
  - stage: stage1
