# Exported from:        http://Sinthuja:5516/
# Release version:      24.3.0-SNAPSHOT
# Date created:         Fri Jul 19 10:56:02 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Pattern_pattern 1.yaml
  - Template_temp2.yaml
  - Trigger_trigger 2.yaml
  - Variables.yaml
  - Workflow_workflow1.yaml
