# Exported from:        http://Sinthuja:5516/
# Release version:      24.3.0-SNAPSHOT
# Date created:         Fri Jul 19 10:56:02 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: fol1/subfol2
spec:
- template: temp2
  scheduledStartDate: 2024-07-19T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: gate
      type: xlrelease.GateTask
    - name: find folder
      type: xlrelease.ScriptTask
      script: |-
        print "getCurrentFolder(): %s" % getCurrentFolder()
        print "getCurrentFolder().id: %s" % getCurrentFolder().id
        print "getCurrentFolder().title: %s" % getCurrentFolder().title
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_temp2_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
