# Exported from:        http://Sinthuja:5516/
# Release version:      24.3.0-SNAPSHOT
# Date created:         Fri Jul 19 10:56:02 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: fol1/subfol2
spec:
- name: trigger 2
  type: git.Poll
  enabled: false
  periodicity: "60"
  releaseTitle: aa
  template: temp2
  gitRepository: git
  commitId: 18c5389e1ba89dd5e0ae7e4a6fd6075c5070264c
