# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Wed Oct 27 18:07:06 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: JKfolder
spec:
- directory: sub1
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.folvar1
- pattern: Pattern_1
  stages:
  - stage: New Stage
    transition:
      name: New Transition
      type: delivery.Transition
      conditions:
      - type: delivery.ConditionGroup
        operator: OR
        conditions:
        - type: delivery.ConditionGroup
          operator: AND
          conditions:
          - type: delivery.ItemsCompletionCondition
  - stage: New Stage (1)
  - stage: New Stage (2)
- pattern: Pattern_1_edited
  stages:
  - stage: New Stage
    transition:
      name: New Transition
      type: delivery.Transition
      conditions:
      - type: delivery.ConditionGroup
        operator: OR
        conditions:
        - type: delivery.ConditionGroup
          operator: AND
          conditions:
          - type: delivery.ItemsCompletionCondition
  - stage: New Stage (1)
  - stage: New Stage (2)
- pattern: pattern 11
  stages:
  - stage: stage1
  - stage: stage2
- pattern: pattern 12
  stages:
  - stage: stage1
  - stage: stage2
  - stage: stage3
- pattern: pattern 177777
  stages:
  - stage: stage2666
  - stage: stage2999909
- template: AAHJ
  scheduledStartDate: 2021-10-19T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- template: CA
  scheduledStartDate: 2021-10-19T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- template: Template
  scheduledStartDate: 2021-10-19T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- template: template1
  scheduledStartDate: 2021-10-19T09:00:00+05:30
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- name: hh
  type: time.Schedule
  releaseTitle: er
  template: CA
  pollType: REPEAT
  periodicity: "3"
  enabled: false
  triggerTime: 2021-10-20T17:34:09.402000
- name: testtrigger
  type: time.Schedule
  releaseTitle: rel1
  template: CA
  pollType: REPEAT
  periodicity: "10"
  enabled: false
  triggerTime: 2021-10-20T17:34:01.989000
- name: ye
  type: time.Schedule
  releaseTitle: nnn
  template: CA
  pollType: REPEAT
  periodicity: "5"
  enabled: false
  triggerTime: 2021-10-20T17:34:29.812000
---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  home: JKfolder
spec:
- directory: "."
  teams:
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#lock_task
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - folder#view
    - release#abort
    - release#edit_task_script
    - release#edit_task_configuration_facet
    - release#edit_task_flag
    - release#edit_task_dates
    - release#edit_task
  - name: Folder Owner
    users:
    - user1
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#create_release
    - template#edit_precondition
    - template#edit_failure_handler
- directory: sub1
  teams:
  - name: Folder Owner
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
  - name: newteam1
    users:
    - admin
    permissions:
    - folder#view
    - folder#edit
    - folder#apply_changes
    - folder#edit_versions
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#lock_task
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - folder#view
    - release#abort
    - release#edit_task_script
    - release#edit_task_configuration_facet
    - release#edit_task_flag
    - release#edit_task_dates
    - release#edit_task
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#create_release
    - template#edit_precondition
    - template#edit_failure_handler
