# Exported from:        http://minserver:5516/
# Release version:      10.3.0-SNAPSHOT
# Date created:         Thu Jul 29 18:28:49 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Versioning test folder
spec:
- pattern: Pattern_1
  stages:
  - stage: New Stage
    transition:
      name: New Transition
      type: delivery.Transition
      conditions:
      - type: delivery.ConditionGroup
        operator: OR
        conditions:
        - type: delivery.ConditionGroup
          operator: AND
          conditions:
          - type: delivery.ItemsCompletionCondition
  - stage: New Stage (1)
  - stage: New Stage (2)
- pattern: Pattern_1_edited
  stages:
  - stage: New Stage
    transition:
      name: New Transition
      type: delivery.Transition
      conditions:
      - type: delivery.ConditionGroup
        operator: OR
        conditions:
        - type: delivery.ConditionGroup
          operator: AND
          conditions:
          - type: delivery.ItemsCompletionCondition
  - stage: New Stage (1)
  - stage: New Stage (2)
