# Exported from:        http://xl-release-nightly.xebialabs.com:5516/
# Release version:      25.1.0-1209.113
# Date created:         Mon Dec 09 12:00:35 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - ' Green.yaml'
  - Notifications.yaml
  - Template_Configure Release.yaml
  - "Template_Deployment pattern: Canary Release.yaml"
  - Template_Guided Tour for Release Managers.yaml
  - Template_Sample Release Template with Digital.ai Deploy.yaml
  - Template_Sample Release Template.yaml
  - Template_Welcome to Release!.yaml
  - Variables.yaml
