# Exported from:        http://xl-release-nightly.xebialabs.com:5516/
# Release version:      25.1.0-1209.113
# Date created:         Mon Dec 09 12:00:34 CET 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: test123
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.git token
    value: !value "xlrelease_PasswordStringVariable_folder_git_token_value"
