# Exported from:        http://minserver:5516/
# Release version:      10.2.0-SNAPSHOT
# Date created:         Tue Jun 29 18:57:05 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder_1
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.ffff
    value: !value "xlrelease_PasswordStringVariable_folder_ffff_value"
  - type: xlrelease.StringVariable
    key: folder.fv
    value: def
- name: fol1_webhook_event
  type: events.PostWebhookEndpoint
  path: github_push2
  authentication:
    type: events.NoAuthentication
- name: git_config_at_folder_level
  type: git.Repository
  variableMapping:
    password: "${global.github_token}"
  url: https://github.com/ASROrg/TestRepo1
  username: sinthujah
  proxyHost: 192.168.0.113
  proxyPort: "80"
  proxyUsername: Administrator
  proxyPassword: !value "git_Repository_git_config_at_folder_level_proxyPassword"
  proxyDomain: WinGate
- name: new connection
  type: git.Repository
  variableMapping:
    password: "${global.github_token}"
  url: https://github.com/Sinthujah/TestRepo
  username: sinthujah
- name: folder_level_jenkins_config
  type: jenkins.Server
  url: http://192.168.0.147:8080
  username: testuser
  password: !value "jenkins_Server_folder_level_jenkins_config_password"
  proxyHost: 192.168.0.113
  proxyPort: "80"
  proxyUsername: Administrator
  proxyPassword: !value "jenkins_Server_folder_level_jenkins_config_proxyPassword"
  proxyDomain: WinGate
- name: folder_level_jira
  type: jira.Server
  variableMapping:
    apiToken: "${global.JiraToken}"
  url: https://digitalai.atlassian.net/
  username: sinthuja@digital.ai
  password: !value "jira_Server_folder_level_jira_password"
  proxyHost: 192.168.0.113
  proxyPort: "80"
  proxyUsername: Administrator
  proxyPassword: !value "jira_Server_folder_level_jira_proxyPassword"
  proxyDomain: WinGate
- name: folder_level_nexus
  type: nexus.Server
  url: http://192.168.0.147:8081/
  username: admin
  password: !value "nexus_Server_folder_level_nexus_password"
  proxyHost: 192.168.0.113
  proxyPort: "80"
  proxyUsername: Administrator
  proxyPassword: !value "nexus_Server_folder_level_nexus_proxyPassword"
  proxyDomain: WinGate
  serverVersion: Nexus v3+
- name: Testing git hub
  type: xlrelease.GitHubScmConnectorConfig
  repository: Sinthujah/TestRepo
  credential:
    type: xlrelease.GitHubOAuth2Token
    token: !value "xlrelease_GitHubOAuth2Token_token"
- pattern: jhkewhf ew fi ewfyewo ffoewf ewyfo ewfoewyf ew foyoewyf oewf ewfoewuofuewo
    ckdsckdshofiuwe foewfw dcwlefoiuewof dchewofcoe o fwlehfohoewfo wef oewfoewuf
    ifbyiewufi ew fef iyewi f ewif yiew fy ewi yfiw yeifdisycidsciewqf ec eofyoewf
    dskcdskvcoiewyovc dskjc
  stages:
  - stage: New Stage
- pattern: pattern1
  stages:
  - stage: New Stage
- template: Template 3
  scheduledStartDate: 2021-06-07T09:00:00+05:30
  dueDate: 2021-06-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: gate task
      type: xlrelease.GateTask
    - name: rrr
      type: xlrelease.Task
  riskProfile: Default risk profile
- template: Template 5
  scheduledStartDate: 2021-06-07T09:00:00+05:30
  dueDate: 2021-06-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: task group
      type: xlrelease.SequentialGroup
      tasks:
      - name: task 1
        type: xlrelease.Task
      - name: task 2
        type: xlrelease.Task
  riskProfile: Default risk profile
- template: Test Template 2
  scheduledStartDate: 2021-04-29T09:00:00+05:30
  dueDate: 2021-04-29T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: Task 12
      type: xlrelease.Task
  riskProfile: Default risk profile
- template: Test template 1
  scheduledStartDate: 2021-04-28T09:00:00+05:30
  dueDate: 2021-04-28T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: "${folder.variable under folder_gr}"
      type: xlrelease.Task
    - name: create release task 1
      type: xlrelease.CreateReleaseTask
      riskProfile: Default risk profile
      template: "${folder.fv}"
      folder: "${folder.fv}"
    - name: jenkins
      type: jenkins.Build
      jenkinsServer: localjenkins
      jobName: test
      variableMapping:
        pythonScript.apiToken: "${folder.ffff}"
    - name: jython task
      type: xlrelease.ScriptTask
      script: print(folderVariables)
  riskProfile: Default risk profile
- template: template 4
  scheduledStartDate: 2021-06-07T09:00:00+05:30
  dueDate: 2021-06-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: task 1
      type: xlrelease.Task
      taskFailureHandlerEnabled: true
      taskRecoverOp: RUN_SCRIPT
    - name: task 2
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: via a task
      riskProfile: Default risk profile
      template: Test Folder/TestTemplate1
      folder: Folder_2
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_template_4_scriptUserPassword"
  riskProfile: Default risk profile
- template: template 6
  scheduledStartDate: 2021-06-07T09:00:00+05:30
  dueDate: 2021-06-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: group 1
      type: xlrelease.ParallelGroup
      tasks:
      - name: tsak 1
        type: xlrelease.Task
      - name: task 2
        type: xlrelease.Task
  riskProfile: Default risk profile
