# Exported from:        http://minserver:5516/
# Release version:      10.2.0-SNAPSHOT
# Date created:         Thu Jul 01 18:30:35 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder_1
spec:
- pattern: jhkewhf ew fi ewfyewo ffoewf ewyfo ewfoewyf ew foyoewyf oewf ewfoewuofuewo
    ckdsckdshofiuwe foewfw dcwlefoiuewof dchewofcoe o fwlehfohoewfo wef oewfoewuf
    ifbyiewufi ew fef iyewi f ewif yiew fy ewi yfiw yeifdisycidsciewqf ec eofyoewf
    dskcdskvcoiewyovc dskjc
  stages:
  - stage: New Stage
- pattern: pattern1
  stages:
  - stage: New Stage
- template: Template 3
  scheduledStartDate: 2021-06-07T09:00:00+05:30
  dueDate: 2021-06-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: gate task
      type: xlrelease.GateTask
    - name: rrr
      type: xlrelease.Task
  riskProfile: Default risk profile
- template: Template 5
  scheduledStartDate: 2021-06-07T09:00:00+05:30
  dueDate: 2021-06-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: task group
      type: xlrelease.SequentialGroup
      tasks:
      - name: task 1
        type: xlrelease.Task
      - name: task 2
        type: xlrelease.Task
  riskProfile: Default risk profile
- template: Test Template 2
  scheduledStartDate: 2021-04-29T09:00:00+05:30
  dueDate: 2021-04-29T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: Task 12
      type: xlrelease.Task
  riskProfile: Default risk profile
- template: Test template 1
  scheduledStartDate: 2021-04-28T09:00:00+05:30
  dueDate: 2021-04-28T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: "${folder.variable under folder_gr}"
      type: xlrelease.Task
    - name: create release task 1
      type: xlrelease.CreateReleaseTask
      riskProfile: Default risk profile
      template: "${folder.fv}"
      folder: "${folder.fv}"
    - name: jenkins
      type: jenkins.Build
      jenkinsServer: localjenkins
      jobName: test
      variableMapping:
        pythonScript.apiToken: "${folder.ffff}"
    - name: jython task
      type: xlrelease.ScriptTask
      script: print(folderVariables)
  riskProfile: Default risk profile
- template: template 4
  scheduledStartDate: 2021-06-07T09:00:00+05:30
  dueDate: 2021-06-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: task 1
      type: xlrelease.Task
      taskFailureHandlerEnabled: true
      taskRecoverOp: RUN_SCRIPT
    - name: task 2
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: via a task
      riskProfile: Default risk profile
      template: Test Folder/TestTemplate1
      folder: Folder_2
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_template_4_scriptUserPassword"
  riskProfile: Default risk profile
- template: template 6
  scheduledStartDate: 2021-06-07T09:00:00+05:30
  dueDate: 2021-06-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: group 1
      type: xlrelease.ParallelGroup
      tasks:
      - name: tsak 1
        type: xlrelease.Task
      - name: task 2
        type: xlrelease.Task
  riskProfile: Default risk profile
- name: Trigger using webhook event
  type: events.EventBasedTrigger
  enabled: false
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: Release created by the webhook event trigger under long folder name
  - type: xlrelease.StringValue
    targetProperty: template
    value: Test template 1
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: Long folder name kdweh12u3oi21embckjfih243iu1834989e3bekj32keh32e9832e21ekj21eh
      e3iu2ye832 ej32geiy328ey9832 iuiu32yeiu32 iueiu32yeiu32e geiu32eiuy32ue iueiu32yeiu32eiu32e
      jchdsiuyfiewy3 22n3iue32e ueiu32iueiu32he32ehjbjbej32eiu32uyei8 iuhduihiuew
      iuei
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: testing webhook
  eventType: events.HttpRequestEvent
- name: Trigger with empty folder test 1
  type: events.EventBasedTrigger
  enabled: false
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: release 1234
  - type: xlrelease.StringValue
    targetProperty: template
    value: Test template 1
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: fol1_webhook_event
  eventType: events.HttpRequestEvent
- name: Webhook event Trigger - no folder selected
  type: events.EventBasedTrigger
  enabled: false
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: Release - no folder selected
  - type: xlrelease.StringValue
    targetProperty: template
    value: Test template 1
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: fol1_webhook_event
  eventType: events.HttpRequestEvent
- name: Git poll trigger - no folder
  type: git.Poll
  description: testing the triggers
  enabled: false
  periodicity: "5"
  releaseTitle: Release created by a trigger 1
  template: Test template 1
  gitRepository: My test git repo
  commitId: b019ebca2e2a3a82282d86acb56294523bed68cb
- name: Trigger 1
  type: git.Poll
  enabled: false
  releaseTitle: release by gr
  template: Test template 1
  releaseFolder: Folder_3
  gitRepository: git_config_at_folder_level
  commitId: b019ebca2e2a3a82282d86acb56294523bed68cb
- name: Trigger 2
  type: git.Poll
  enabled: false
  releaseTitle: Release to be created under 'folder3' by the trigger
  template: Test template 1
  releaseFolder: Folder_3
  gitRepository: git_config_at_folder_level
  commitId: b019ebca2e2a3a82282d86acb56294523bed68cb
