# Exported from:        http://minserver:5516/
# Release version:      10.3.0-SNAPSHOT
# Date created:         Tue Sep 28 16:45:43 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Version Control
spec:
- template: new template 1
  scheduledStartDate: 2021-09-28T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: task1
      type: xlrelease.Task
  riskProfile: Default risk profile
