# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Mon Dec 27 16:50:28 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Base Data
spec:
- name: Local Git repo
  type: git.Repository
  variableMapping:
    password: "${global.github token}"
  url: https://github.com/Sinthujah/TestRepo
  username: sinthujah
- name: Local Jenkins
  type: jenkins.Server
  variableMapping:
    password: "${global.github token}"
  url: https://jenkins.com
  username: sinthuja
- name: git trigger
  type: git.Poll
  releaseTitle: ccc
  variables:
  - type: xlrelease.ListStringVariable
    key: Multiselectvar4
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - ee
      - rr
      - tt
    value:
    - ee
    - rr
  - type: xlrelease.ListStringVariable
    key: Multiselectvar5
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - uu
      - ii
      - oo
    value:
    - uu
  template: Template 4
  gitRepository: Local Git repo
  username: sinthujah
  password: !value "git_Poll_git_trigger_password"
