# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Mon Dec 27 16:29:27 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Base Data
spec:
- name: Local Git repo
  type: git.Repository
  variableMapping:
    password: "${global.github token}"
  url: https://github.com/Sinthujah/TestRepo
  username: sinthujah
- name: Local Jenkins
  type: jenkins.Server
  url: https://jenkins.com
- pattern: pattern T
  stages:
  - stage: New Stage
