# Exported from:        http://minserver:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Mon Dec 27 14:57:56 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Base Data
spec:
- name: git trigger
  type: git.Poll
  enabled: false
  releaseTitle: rrrrrrrrrrrr
  variables:
  - type: xlrelease.IntegerVariable
    key: Numbers trigger 3
    value: 4
  - type: xlrelease.BooleanVariable
    key: Checkbox variable 2
  - type: xlrelease.StringVariable
    key: listbox variable
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - ffff
    value: ffff
  - type: xlrelease.StringVariable
    key: listbox variable 2
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - ggg
    value: ggg
  template: Template 2
  gitRepository: Global Git repo
- name: Jira trigger
  type: jira.IssueTrigger
  enabled: false
  releaseTitle: sss
  variables:
  - type: xlrelease.StringVariable
    key: text
    value: dddd
  template: Template 3
  jql: dewd
  server: jira
- name: Nexus trigger
  type: nexus.PublishedArtifact
  enabled: false
  releaseTitle: sss
  variables:
  - type: xlrelease.ListStringVariable
    key: Multiselectvar4
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - ee
      - rr
      - tt
    value:
    - ee
    - rr
  template: Template 4
  groupId: dd
  artifactId: dd
  server: Nexus
  repositoryId: sss
- name: svn trigger
  type: svn.Poll
  enabled: false
  releaseTitle: rel3
  variables:
  - type: xlrelease.BooleanVariable
    key: Checkbox variable
    value: true
  - type: xlrelease.BooleanVariable
    key: Checkbox variable 2
  - type: xlrelease.StringVariable
    key: listbox variable
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - ffff
    value: ffff
  - type: xlrelease.IntegerVariable
    key: Numbers trigger 3
    value: 4
  template: Template 2
  svnRepository: svn
- name: svn trigger with template5
  type: svn.Poll
  enabled: false
  releaseTitle: qqq
  variables:
  - type: xlrelease.StringVariable
    key: Listbox5
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - ww
    value: ww
  template: Template 5
  svnRepository: svn
- name: TIme trigger
  type: time.Schedule
  releaseTitle: rel1
  variables:
  - type: xlrelease.StringVariable
    key: text variable
    value: textdefault
  - type: xlrelease.StringVariable
    key: listbox variable
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - val1
    value: val1
  - type: xlrelease.ListStringVariable
    key: multi select variable
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - t1
      - t2
    value:
    - t1
  template: Template1
  pollType: REPEAT
  periodicity: "120"
  enabled: false
  triggerTime: 2021-12-23T18:31:00.472000
- name: Time trigger 2
  type: time.Schedule
  releaseTitle: rel2
  variables:
  - type: xlrelease.StringVariable
    key: text variable
    value: textdefaultedited
  - type: xlrelease.StringVariable
    key: listbox variable
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - val1
    value: val1
  - type: xlrelease.ListStringVariable
    key: multi select variable
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - t1
      - t2
    value:
    - t2
  template: Template1
  pollType: REPEAT
  periodicity: "120"
  enabled: false
  triggerTime: 2021-12-23T18:30:35.016000
- name: time trigger with diff variables
  type: time.Schedule
  releaseTitle: rrrr
  variables:
  - type: xlrelease.BooleanVariable
    key: Checkbox variable
    value: true
  - type: xlrelease.BooleanVariable
    key: Checkbox variable 2
  - type: xlrelease.StringVariable
    key: listbox variable
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - ffff
    value: ffff
  - type: xlrelease.IntegerVariable
    key: Numbers trigger 3
    value: 4
  template: Template 2
  pollType: REPEAT
  periodicity: "234"
  enabled: false
  triggerTime: 2021-12-23T15:44:49.381000
